settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
- name: service_init
  run_list:
  - recipe[chef-client::config]
  - recipe[chef-client::init_service]
#  includes: ["ubuntu-12.04", "ubuntu-14.04", "centos-6"]

- name: service_upstart
  run_list:
  - recipe[chef-client::upstart_service]
#  includes: ["ubuntu-12.04", "ubuntu-14.04"]

- name: cron
  run_list:
  - recipe[cron::default]
  - recipe[chef-client::cron]

- name: config
  run_list:
  - recipe[chef-client::config]

- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]

- name: upgrade
  steps:
  - run_list:
    - recipe[chef-client::config]
    - recipe[chef-client::upstart_service]
    provisioner:
      name: chef_interval
      require_chef_omnibus: 11.18.12
    attributes:
      chef_client:
        log_dir: /var/log/chef
  - run_list:
    - recipe[chef-client::config]
    - recipe[chef-client::upstart_service]
    - recipe[omnibus_updater]
    provisioner:
      name: chef_interval
      require_chef_omnibus: 11.18.12
    attributes:
      omnibus_updater:
        restart_chef_service: true
#        pid_file: /run/chef/client.pid
